2025-07-30 03:21:42,230 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 02:58:56,579 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:01:58,320 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:04:07,191 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:13:41,775 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:13:43,131 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:13:44,483 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:14:40,546 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:14:57,213 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:14:58,760 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:15:56,152 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:16:22,933 ERROR: Exception on /register [POST] [in C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\wtforms\validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\night\OneDrive\Desktop\Microblog\app\routes.py", line 55, in register
    if form.validate_on_submit():
       ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\flask_wtf\form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
                                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\wtforms\form.py", line 330, in validate
    return super().validate(extra)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\wtforms\form.py", line 147, in validate
    if not field.validate(self, extra):
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\wtforms\fields\core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\wtforms\fields\core.py", line 254, in _run_validation_chain
    validator(form, self)
    ~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\night\OneDrive\Desktop\Microblog\.venv\Lib\site-packages\wtforms\validators.py", line 403, in __call__
    raise Exception(
        "Install 'email_validator' for email validation support."
    ) from exc
Exception: Install 'email_validator' for email validation support.
2025-08-03 03:17:53,544 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:42:18,973 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 03:59:14,197 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
2025-08-03 04:00:45,098 INFO: Microblog startup [in C:\Users\night\OneDrive\Desktop\Microblog\app\__init__.py:43]
